# Generated by Django 4.2.11 on 2024-08-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=300)),
                ('fechaNacimiento', models.DateField()),
                ('fechaFallecimiento', models.DateField(blank=True, null=True)),
                ('pequenaBiografia', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.TextField(max_length=300),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='myapp.autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(related_name='libros', to='myapp.genero'),
        ),
    ]
