# Generated by Django 4.2.11 on 2024-09-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_autor_genero_alter_libro_nombre_libro_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(default='autores/defecto.png', upload_to='autores/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default='Descripción no disponible', max_length=500),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.TextField(max_length=150),
        ),
    ]
