# Generated by Django 4.2.11 on 2024-09-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_inventario_historialinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imgPortada',
            field=models.ImageField(default='libros/defectoLibro.png', upload_to='libros/'),
        ),
    ]
