# Generated by Django 4.2.11 on 2024-09-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.rol'),
        ),
    ]
